services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./laravel/:/app
    networks:
      - laravel-net

  php:
    image: laravel-php:latest
    command: ["sh", "/app/entrypoint.sh"]
    volumes:
      - ./laravel/:/app
    networks:
      - laravel-net
    deploy:
      replicas: 3
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel-net

volumes:
  pgdata:

networks:
  laravel-net:
    driver: overlay
