- name: Copy application code to remote server
  synchronize:
    src: "{{ playbook_dir }}/../../laravel/"
    dest: "{{ default_deploy_path }}/portfolio/laravel"
    recursive: yes
    delete: yes

- name: Copy docker-compose.yml
  copy:
    src: "{{ playbook_dir }}/../../docker-compose.yml"
    dest: "{{ default_deploy_path }}/portfolio/docker-compose.yml"

- name: Copy nginx.conf
  copy:
    src: "{{ playbook_dir }}/../../nginx.conf"
    dest: "{{ default_deploy_path }}/portfolio/nginx.conf"