- name: Check if .env file exists
  stat:
    path: "{{ default_deploy_path }}/portfolio/laravel/.env"
  register: env_file

- name: Copy .env.example to .env if .env does not exist
  copy:
    src: "{{ playbook_dir }}/../../laravel/.env.example"
    dest: "{{ default_deploy_path }}/portfolio/laravel/.env"
    remote_src: no
  when: not env_file.stat.exists

- name: Set environment variables in .env
  lineinfile:
    path: "{{ default_deploy_path }}/portfolio/laravel/.env"
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
    create: yes
  loop:
    - { key: "DB_CONNECTION", value: "pgsql" }
    - { key: "DB_HOST", value: "db" }
    - { key: "DB_PORT", value: "5432" }
    - { key: "DB_DATABASE", value: "laravel" }
    - { key: "DB_USERNAME", value: "laravel" }
    - { key: "DB_PASSWORD", value: "secret" }
    - { key: "APP_URL", value: "http://localhost:8080" }
