- name: Deploy Laravel App with Docker on VPS
  hosts: vps
  become: true

  vars:
    ssh_user: "{{ lookup('env', 'SSH_USER') }}"
    base_path: "/home/{{ ssh_user }}"
    app_path: "{{ base_path }}/laravel"

  tasks:
    - name: Ensure Laravel app directory exists
      file:
        path: "{{ app_path }}"
        state: directory
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0755"

    - name: Sync Laravel app code
      synchronize:
        src: "{{ playbook_dir }}/../laravel/"
        dest: "{{ app_path }}/"
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=node_modules"
          - "--delete"

    - name: Copy docker-compose.yml to VPS
      copy:
        src: "{{ playbook_dir }}/../docker-compose.yml"
        dest: "{{ base_path }}/docker-compose.yml"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0644"

    - name: Copy entrypoint.sh
      copy:
        src: "{{ playbook_dir }}/../entrypoint.sh"
        dest: "{{ base_path }}/entrypoint.sh"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0755"

    - name: Copy nginx.conf
      copy:
        src: "{{ playbook_dir }}/../nginx.conf"
        dest: "{{ base_path }}/nginx.conf"
        owner: "{{ ssh_user }}"
        group: "{{ ssh_user }}"
        mode: "0644"

    - name: Pull and start Docker containers
      command: docker compose up -d
      args:
        chdir: "{{ base_path }}"
