name: Deploy Laravel App via Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create dynamic inventory file
        run: |
          echo "[web]" > ansible/inventory/hosts
          echo "${{ secrets.SSH_HOST }}" >> ansible/inventory/hosts


      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts ansible/playbooks/laravel-deploy.yml \
            --user ${{ secrets.SSH_USER }} \
            --private-key ~/.ssh/id_rsa