name: Build, Test and Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Deploy (placeholder)
          run: echo "🚀 build ..."

  test:
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: laravel
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml, curl, zip, pdo, pgsql
          tools: composer

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env
        run: cp .env.example .env

      - name: Set environment for PostgreSQL
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=laravel" >> .env
          echo "DB_USERNAME=laravel" >> .env
          echo "DB_PASSWORD=secret" >> .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations and tests
        run: |
          php artisan migrate --force
          php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy (placeholder)
        run: echo "🚀 Deploying to production server..."
