name: Build, Test and Deploy Laravel App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: |
          echo "Checking out code..."

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        run: |
        echo "Checking out code..."

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: deploy
        run: |
          echo "Deploying to production server..."
